In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
movies = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\AIML\Practice\Datasets\Movie recommendation\movies_metadata.csv", low_memory=False)
ratings = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\AIML\Practice\Datasets\Movie recommendation\ratings.csv")
keywords = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\AIML\Practice\Datasets\Movie recommendation\keywords.csv")
links = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\AIML\Practice\Datasets\Movie recommendation\links.csv")
credits = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\AIML\Practice\Datasets\Movie recommendation\credits.csv")

In [3]:
print(movies.shape)
print(keywords.shape)
print(credits.shape)
print(links.shape)
print(ratings.shape)

(45466, 24)
(46419, 2)
(45476, 3)
(45843, 3)
(26024289, 4)

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [5]:
movies = movies[movies['id'].str.isnumeric()].copy()
movies['id'] = movies['id'].astype(int)

In [6]:
movies['budget'] = pd.to_numeric(movies['budget'], errors='coerce')
movies['popularity'] = pd.to_numeric(movies['popularity'], errors='coerce')

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45463 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45463 non-null  object
 1   belongs_to_collection  4491 non-null   object
 2   budget                 45463 non-null  int64
 3   genres                 45463 non-null  object
 4   homepage               7779 non-null   object
 5   id                     45463 non-null  int64
 6   imdb_id                45446 non-null  object
 7   original_language      45452 non-null  object
 8   original_title         45463 non-null  object
 9   overview               44509 non-null  object
 10  popularity             45460 non-null  float64
 11  poster_path            45077 non-null  object
 12  production_companies   45460 non-null  object
 13  production_countries   45460 non-null  object
 14  release_date           45376 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(5), int64(2), object(17)
memory usage: 8.7+ MB

In [8]:
keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  object
dtypes: int64(1), object(1)
memory usage: 725.4+ KB

In [9]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [10]:
movies = movies.merge(keywords, on='id')
movies = movies.merge(credits, on='id')

In [11]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46628 entries, 0 to 46627
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  46628 non-null  object
 1   belongs_to_collection  4574 non-null   object
 2   budget                 46628 non-null  int64
 3   genres                 46628 non-null  object
 4   homepage               8009 non-null   object
 5   id                     46628 non-null  int64
 6   imdb_id                46611 non-null  object
 7   original_language      46617 non-null  object
 8   original_title         46628 non-null  object
 9   overview               45633 non-null  object
 10  popularity             46624 non-null  float64
 11  poster_path            46229 non-null  object
 12  production_companies   46624 non-null  object
 13  production_countries   46624 non-null  object
 14  release_date           46540 non-null  object
 15  revenue                46624 non-null  float64
 16  runtime                46360 non-null  float64
 17  spoken_languages       46624 non-null  object
 18  status                 46542 non-null  object
 19  tagline                20783 non-null  object
 20  title                  46624 non-null  object
 21  video                  46624 non-null  object
 22  vote_average           46624 non-null  float64
 23  vote_count             46624 non-null  float64
 24  keywords               46628 non-null  object
 25  cast                   46628 non-null  object
 26  crew                   46628 non-null  object
dtypes: float64(5), int64(2), object(20)
memory usage: 9.6+ MB

In [12]:
links.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45843 entries, 0 to 45842
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  45843 non-null  int64
 1   imdbId   45843 non-null  int64
 2   tmdbId   45624 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 1.0 MB

In [13]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 794.2 MB

In [14]:
links = links.dropna(subset=['tmdbId']).copy()
links['tmdbId'] = links['tmdbId'].astype(int)

In [15]:
links.head()

   movieId  imdbId  tmdbId
0        1  114709     862
1        2  113497    8844
2        3  113228   15602
3        4  114885   31357
4        5  113041   11862

In [16]:
movies = movies.merge(
    links,
    left_on='id',
    right_on='tmdbId',
    how='inner'
)

In [17]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [18]:
ratings_summary = ratings.groupby('movieId').agg(
    avg_rating=('rating', 'mean'),
    rating_count=('rating', 'count')
).reset_index()

In [19]:
ratings_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45115 entries, 0 to 45114
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movieId       45115 non-null  int64
 1   avg_rating    45115 non-null  float64
 2   rating_count  45115 non-null  int64
dtypes: float64(1), int64(2)
memory usage: 1.0 MB

In [20]:
ratings_summary.head()

   movieId  avg_rating  rating_count
0        1    3.888157         66008
1        2    3.236953         26060
2        3    3.175550         15497
3        4    2.875713          2981
4        5    3.079565         15258

In [21]:
movies = movies.merge(
    ratings_summary,
    on='movieId',
    how='left'
)

In [22]:
movies['avg_rating'] = movies['avg_rating'].fillna(0)
movies['rating_count'] = movies['rating_count'].fillna(0)

In [23]:
movies.shape

(46910, 32)

In [24]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46910 entries, 0 to 46909
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  46910 non-null  object
 1   belongs_to_collection  4602 non-null   object
 2   budget                 46910 non-null  int64
 3   genres                 46910 non-null  object
 4   homepage               8049 non-null   object
 5   id                     46910 non-null  int64
 6   imdb_id                46893 non-null  object
 7   original_language      46899 non-null  object
 8   original_title         46910 non-null  object
 9   overview               45915 non-null  object
 10  popularity             46906 non-null  float64
 11  poster_path            46511 non-null  object
 12  production_companies   46906 non-null  object
 13  production_countries   46906 non-null  object
 14  release_date           46822 non-null  object
 15  revenue                46906 non-null  float64
 16  runtime                46642 non-null  float64
 17  spoken_languages       46906 non-null  object
 18  status                 46824 non-null  object
 19  tagline                20909 non-null  object
 20  title                  46906 non-null  object
 21  video                  46906 non-null  object
 22  vote_average           46906 non-null  float64
 23  vote_count             46906 non-null  float64
 24  keywords               46910 non-null  object
 25  cast                   46910 non-null  object
 26  crew                   46910 non-null  object
 27  movieId                46910 non-null  int64
 28  imdbId                 46910 non-null  int64
 29  tmdbId                 46910 non-null  int64
 30  avg_rating             46910 non-null  float64
 31  rating_count           46910 non-null  float64
dtypes: float64(7), int64(5), object(20)
memory usage: 11.5+ MB

In [25]:
movies[['title', 'avg_rating', 'rating_count']].head()

                         title  avg_rating  rating_count
0                    Toy Story    3.888157       66008.0
1                      Jumanji    3.236953       26060.0
2             Grumpier Old Men    3.175550       15497.0
3            Waiting to Exhale    2.875713        2981.0
4  Father of the Bride Part II    3.079565       15258.0

In [26]:
wiki = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\AIML\Practice\Datasets\Movie recommendation\wiki_movie_plots_deduped.csv")
wiki.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34886 entries, 0 to 34885
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Release Year      34886 non-null  int64
 1   Title             34886 non-null  object
 2   Origin/Ethnicity  34886 non-null  object
 3   Director          34886 non-null  object
 4   Cast              33464 non-null  object
 5   Genre             34886 non-null  object
 6   Wiki Page         34886 non-null  object
 7   Plot              34886 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.1+ MB

In [27]:
wiki = wiki[
    ['Title', 'Release Year', 'Plot', 'Origin/Ethnicity', 'Wiki Page']
].copy()

In [28]:
movies['title_clean'] = movies['title'].str.lower().str.strip()
wiki['title_clean'] = wiki['Title'].str.lower().str.strip()

In [29]:
movies['release_date'].head()

0    1995-10-30
1    1995-12-15
2    1995-12-22
3    1995-12-22
4    1995-02-10
Name: release_date, dtype: object

In [30]:
movies['year'] = pd.to_datetime(
    movies['release_date'],
    errors='coerce'
).dt.year

In [31]:
wiki['year'] = pd.to_numeric(
    wiki['Release Year'],
    errors='coerce'
)

In [32]:
movies = movies.merge(
    wiki,
    on=['title_clean', 'year'],
    how='left'
)

In [33]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47084 entries, 0 to 47083
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  47084 non-null  object
 1   belongs_to_collection  4638 non-null   object
 2   budget                 47084 non-null  int64
 3   genres                 47084 non-null  object
 4   homepage               8125 non-null   object
 5   id                     47084 non-null  int64
 6   imdb_id                47067 non-null  object
 7   original_language      47073 non-null  object
 8   original_title         47084 non-null  object
 9   overview               46089 non-null  object
 10  popularity             47080 non-null  float64
 11  poster_path            46685 non-null  object
 12  production_companies   47080 non-null  object
 13  production_countries   47080 non-null  object
 14  release_date           46996 non-null  object
 15  revenue                47080 non-null  float64
 16  runtime                46816 non-null  float64
 17  spoken_languages       47080 non-null  object
 18  status                 46998 non-null  object
 19  tagline                21044 non-null  object
 20  title                  47080 non-null  object
 21  video                  47080 non-null  object
 22  vote_average           47080 non-null  float64
 23  vote_count             47080 non-null  float64
 24  keywords               47084 non-null  object
 25  cast                   47084 non-null  object
 26  crew                   47084 non-null  object
 27  movieId                47084 non-null  int64
 28  imdbId                 47084 non-null  int64
 29  tmdbId                 47084 non-null  int64
 30  avg_rating             47084 non-null  float64
 31  rating_count           47084 non-null  float64
 32  title_clean            47080 non-null  object
 33  year                   46996 non-null  float64
 34  Title                  15212 non-null  object
 35  Release Year           15212 non-null  float64
 36  Plot                   15212 non-null  object
 37  Origin/Ethnicity       15212 non-null  object
 38  Wiki Page              15212 non-null  object
dtypes: float64(9), int64(5), object(25)
memory usage: 14.0+ MB

In [34]:
movies.shape

(47084, 39)

In [35]:
movies[['title_clean', 'year']].duplicated().sum()

np.int64(1705)

In [36]:
movies = movies.drop_duplicates(
    subset=['title_clean', 'year'],
    keep='first'
).copy()

In [37]:
movies.shape

(45379, 39)

In [38]:
movies[['title_clean', 'year']].duplicated().sum()

np.int64(0)

In [39]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45379 entries, 0 to 47083
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45379 non-null  object
 1   belongs_to_collection  4485 non-null   object
 2   budget                 45379 non-null  int64
 3   genres                 45379 non-null  object
 4   homepage               7766 non-null   object
 5   id                     45379 non-null  int64
 6   imdb_id                45362 non-null  object
 7   original_language      45368 non-null  object
 8   original_title         45379 non-null  object
 9   overview               44426 non-null  object
 10  popularity             45378 non-null  float64
 11  poster_path            44996 non-null  object
 12  production_companies   45378 non-null  object
 13  production_countries   45378 non-null  object
 14  release_date           45294 non-null  object
 15  revenue                45378 non-null  float64
 16  runtime                45122 non-null  float64
 17  spoken_languages       45378 non-null  object
 18  status                 45297 non-null  object
 19  tagline                20391 non-null  object
 20  title                  45378 non-null  object
 21  video                  45378 non-null  object
 22  vote_average           45378 non-null  float64
 23  vote_count             45378 non-null  float64
 24  keywords               45379 non-null  object
 25  cast                   45379 non-null  object
 26  crew                   45379 non-null  object
 27  movieId                45379 non-null  int64
 28  imdbId                 45379 non-null  int64
 29  tmdbId                 45379 non-null  int64
 30  avg_rating             45379 non-null  float64
 31  rating_count           45379 non-null  float64
 32  title_clean            45378 non-null  object
 33  year                   45294 non-null  float64
 34  Title                  14741 non-null  object
 35  Release Year           14741 non-null  float64
 36  Plot                   14741 non-null  object
 37  Origin/Ethnicity       14741 non-null  object
 38  Wiki Page              14741 non-null  object
dtypes: float64(9), int64(5), object(25)
memory usage: 13.8+ MB

In [40]:
drop_cols = [
    'adult',
    'homepage',
    'poster_path',
    'video',
    'imdb_id',
    'imdbId',
    'tmdbId',
    'belongs_to_collection',
    'tagline',
    'Title',
    'Release Year',
    'Wiki Page'
]

In [41]:
movies = movies.drop(columns=drop_cols, errors='ignore')

In [42]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45379 entries, 0 to 47083
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                45379 non-null  int64
 1   genres                45379 non-null  object
 2   id                    45379 non-null  int64
 3   original_language     45368 non-null  object
 4   original_title        45379 non-null  object
 5   overview              44426 non-null  object
 6   popularity            45378 non-null  float64
 7   production_companies  45378 non-null  object
 8   production_countries  45378 non-null  object
 9   release_date          45294 non-null  object
 10  revenue               45378 non-null  float64
 11  runtime               45122 non-null  float64
 12  spoken_languages      45378 non-null  object
 13  status                45297 non-null  object
 14  title                 45378 non-null  object
 15  vote_average          45378 non-null  float64
 16  vote_count            45378 non-null  float64
 17  keywords              45379 non-null  object
 18  cast                  45379 non-null  object
 19  crew                  45379 non-null  object
 20  movieId               45379 non-null  int64
 21  avg_rating            45379 non-null  float64
 22  rating_count          45379 non-null  float64
 23  title_clean           45378 non-null  object
 24  year                  45294 non-null  float64
 25  Plot                  14741 non-null  object
 26  Origin/Ethnicity      14741 non-null  object
dtypes: float64(8), int64(3), object(16)
memory usage: 9.7+ MB

In [43]:
movies['title'] = movies['title'].fillna('')
movies['overview'] = movies['overview'].fillna('')
movies['Plot'] = movies['Plot'].fillna('')
movies['original_language'] = movies['original_language'].fillna('unknown')

movies['runtime'] = movies['runtime'].fillna(0)
movies['popularity'] = movies['popularity'].fillna(0)
movies['vote_average'] = movies['vote_average'].fillna(0)
movies['vote_count'] = movies['vote_count'].fillna(0)
movies['avg_rating'] = movies['avg_rating'].fillna(0)
movies['rating_count'] = movies['rating_count'].fillna(0)
movies['year'] = movies['year'].fillna(0)

In [44]:
movies['final_plot'] = movies['Plot']
movies.loc[movies['final_plot'] == '', 'final_plot'] = movies['overview']

In [45]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45379 entries, 0 to 47083
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                45379 non-null  int64
 1   genres                45379 non-null  object
 2   id                    45379 non-null  int64
 3   original_language     45379 non-null  object
 4   original_title        45379 non-null  object
 5   overview              45379 non-null  object
 6   popularity            45379 non-null  float64
 7   production_companies  45378 non-null  object
 8   production_countries  45378 non-null  object
 9   release_date          45294 non-null  object
 10  revenue               45378 non-null  float64
 11  runtime               45379 non-null  float64
 12  spoken_languages      45378 non-null  object
 13  status                45297 non-null  object
 14  title                 45379 non-null  object
 15  vote_average          45379 non-null  float64
 16  vote_count            45379 non-null  float64
 17  keywords              45379 non-null  object
 18  cast                  45379 non-null  object
 19  crew                  45379 non-null  object
 20  movieId               45379 non-null  int64
 21  avg_rating            45379 non-null  float64
 22  rating_count          45379 non-null  float64
 23  title_clean           45378 non-null  object
 24  year                  45379 non-null  float64
 25  Plot                  45379 non-null  object
 26  Origin/Ethnicity      14741 non-null  object
 27  final_plot            45379 non-null  object
dtypes: float64(8), int64(3), object(17)
memory usage: 11.0+ MB

In [55]:
movies['crew'][1]

"[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'department': 'Production', 'gender': 2, 'id': 511, 'job': 'Executive Producer', 'name': 'Larry J. Franco', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7c89', 'department': 'Writing', 'gender': 2, 'id': 876, 'job': 'Screenplay', 'name': 'Jonathan Hensleigh', 'profile_path': '/l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7cdd', 'department': 'Sound', 'gender': 2, 'id': 1729, 'job': 'Original Music Composer', 'name': 'James Horner', 'profile_path': '/oLOtXxXsYk8X4qq0ud4xVypXudi.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7c7d', 'department': 'Directing', 'gender': 2, 'id': 4945, 'job': 'Director', 'name': 'Joe Johnston', 'profile_path': '/fok4jaO62v5IP6hkpaaAcXuw2H.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7cd7', 'department': 'Editing', 'gender': 2, 'id': 4951, 'job': 'Editor', 'name': 'Robert Dalva', 'profile_path': None}, {'credit_id': '573523bec3a368025100062c', 'department': 'Production', 'gender': 0, 'id': 4952, 'job': 'Casting', 'name': 'Nancy Foy', 'profile_path': '/blCkmS4dqNsbPGuQfozHE6wgWBw.jpg'}, {'credit_id': '5722a924c3a3682d1e000b41', 'department': 'Visual Effects', 'gender': 0, 'id': 8023, 'job': 'Animation Supervisor', 'name': 'Kyle Balda', 'profile_path': '/jR8iAP6uC0V42KbUG87qBIUO3Hj.jpg'}, {'credit_id': '52fe44c0c3a36847f80a7ce3', 'department': 'Art', 'gender': 2, 'id': 9967, 'job': 'Production Design', 'name': 'James D. Bissell', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7cb9', 'department': 'Production', 'gender': 2, 'id': 9184, 'job': 'Producer', 'name': 'Scott Kroopf', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7ccb', 'department': 'Production', 'gender': 2, 'id': 9196, 'job': 'Executive Producer', 'name': 'Ted Field', 'profile_path': '/qmB7sZcgRUq7mRFBSTlSsVXh7sH.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7cc5', 'department': 'Production', 'gender': 2, 'id': 18389, 'job': 'Executive Producer', 'name': 'Robert W. Cort', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7cbf', 'department': 'Camera', 'gender': 2, 'id': 11371, 'job': 'Director of Photography', 'name': 'Thomas E. Ackerman', 'profile_path': '/xFDbxk53icM1ofL4iCIwB4GkUxN.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7c83', 'department': 'Writing', 'gender': 2, 'id': 42356, 'job': 'Novel', 'name': 'Chris van Allsburg', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7cb3', 'department': 'Production', 'gender': 2, 'id': 42357, 'job': 'Producer', 'name': 'William Teitler', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7c8f', 'department': 'Writing', 'gender': 2, 'id': 56520, 'job': 'Screenplay', 'name': 'Greg Taylor', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7c95', 'department': 'Writing', 'gender': 2, 'id': 56521, 'job': 'Screenplay', 'name': 'Jim Strain', 'profile_path': None}]"

In [50]:
def extract_names(text):
    try:
        items = ast.literal_eval(text)
        names = [i['name'] for i in items]
        return " ".join(names)
    except:
        return ""

In [52]:
movies['genres_clean'] = movies['genres'].apply(extract_names)
movies['keywords_clean'] = movies['keywords'].apply(extract_names)
movies['cast_clean'] = movies['cast'].apply(extract_names)

In [58]:
movies['cast_clean'].head()

0    Tom Hanks Tim Allen Don Rickles Jim Varney Wal...
1    Robin Williams Jonathan Hyde Kirsten Dunst Bra...
2    Walter Matthau Jack Lemmon Ann-Margret Sophia ...
3    Whitney Houston Angela Bassett Loretta Devine ...
4    Steve Martin Diane Keaton Martin Short Kimberl...
Name: cast_clean, dtype: object

In [59]:
def extract_director(text):
    try:
        items = ast.literal_eval(text)
        names = [i['name'] for i in items if i['job'] == 'Director']
        return " ".join(names)
    except:
        return ""

In [60]:
movies['director_clean'] = movies['crew'].apply(extract_director)

In [61]:
movies['director_clean'].head()

0      John Lasseter
1       Joe Johnston
2      Howard Deutch
3    Forest Whitaker
4      Charles Shyer
Name: director_clean, dtype: object

In [62]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45379 entries, 0 to 47083
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                45379 non-null  int64
 1   genres                45379 non-null  object
 2   id                    45379 non-null  int64
 3   original_language     45379 non-null  object
 4   original_title        45379 non-null  object
 5   overview              45379 non-null  object
 6   popularity            45379 non-null  float64
 7   production_companies  45378 non-null  object
 8   production_countries  45378 non-null  object
 9   release_date          45294 non-null  object
 10  revenue               45378 non-null  float64
 11  runtime               45379 non-null  float64
 12  spoken_languages      45378 non-null  object
 13  status                45297 non-null  object
 14  title                 45379 non-null  object
 15  vote_average          45379 non-null  float64
 16  vote_count            45379 non-null  float64
 17  keywords              45379 non-null  object
 18  cast                  45379 non-null  object
 19  crew                  45379 non-null  object
 20  movieId               45379 non-null  int64
 21  avg_rating            45379 non-null  float64
 22  rating_count          45379 non-null  float64
 23  title_clean           45378 non-null  object
 24  year                  45379 non-null  float64
 25  Plot                  45379 non-null  object
 26  Origin/Ethnicity      14741 non-null  object
 27  final_plot            45379 non-null  object
 28  genres_clean          45379 non-null  object
 29  keywords_clean        45379 non-null  object
 30  cast_clean            45379 non-null  object
 31  director_clean        45379 non-null  object
dtypes: float64(8), int64(3), object(21)
memory usage: 12.4+ MB

In [63]:
print(movies[['genres_clean','keywords_clean','cast_clean','director_clean','final_plot']].head())

               genres_clean  \
0   Animation Comedy Family
1  Adventure Fantasy Family
2            Romance Comedy
3      Comedy Drama Romance
4                    Comedy

                                      keywords_clean  \
0  jealousy toy boy friendship friends rivalry bo...
1  board game disappearance based on children's b...
2   fishing best friend duringcreditsstinger old men
3  based on novel interracial relationship single...
4  baby midlife crisis confidence aging daughter ...

                                          cast_clean   director_clean  \
0  Tom Hanks Tim Allen Don Rickles Jim Varney Wal...    John Lasseter
1  Robin Williams Jonathan Hyde Kirsten Dunst Bra...     Joe Johnston
2  Walter Matthau Jack Lemmon Ann-Margret Sophia ...    Howard Deutch
3  Whitney Houston Angela Bassett Loretta Devine ...  Forest Whitaker
4  Steve Martin Diane Keaton Martin Short Kimberl...    Charles Shyer

                                          final_plot
0  In a world where toys are living things who pr...
1  In 1869, near Brantford, New Hampshire, two br...
2  The feud between Max (Walter Matthau) and John...
3  "Friends are the People who let you be yoursel...
4  The film begins five years after the events of...

In [69]:
movies['combined_text'] = (
    movies['title'] + ' ' + movies['title'] + ' ' +
    movies['genres_clean'] + ' ' + movies['genres_clean'] + ' ' +
    movies['keywords_clean'] + ' ' +
    movies['cast_clean'] + ' ' +
    movies['director_clean'] + ' ' +
    movies['final_plot']
)

In [70]:
movies['combined_text'] = movies['combined_text'].str.replace(r'\s+', ' ', regex=True).str.strip()

In [71]:
movies[['title', 'combined_text']].head()

,title,combined_text
0,Toy Story,Toy Story Toy Story Animation Comedy Family An...
1,Jumanji,Jumanji Jumanji Adventure Fantasy Family Adven...
2,Grumpier Old Men,Grumpier Old Men Grumpier Old Men Romance Come...
3,Waiting to Exhale,Waiting to Exhale Waiting to Exhale Comedy Dra...
4,Father of the Bride Part II,Father of the Bride Part II Father of the Brid...

In [72]:
movies['combined_text'].iloc[0]

"Toy Story Toy Story Animation Comedy Family Animation Comedy Family jealousy toy boy friendship friends rivalry boy next door new toy toy comes to life Tom Hanks Tim Allen Don Rickles Jim Varney Wallace Shawn John Ratzenberger Annie Potts John Morris Erik von Detten Laurie Metcalf R. Lee Ermey Sarah Freeman Penn Jillette John Lasseter In a world where toys are living things who pretend to be lifeless when humans are present, a group of toys, owned by six-year-old Andy Davis, are caught off-guard when Andy's birthday party is moved up a week, as Andy, his mother, and infant sister Molly, are preparing to move the following week. The toys' leader and Andy's favorite toy, a pull-string cowboy doll named Sheriff Woody, organizes the other toys, including Bo Peep the shepherdess, Mr. Potato Head, Rex the Dinosaur, Hamm the Piggy Bank, and Slinky Dog, into a scouting mission. Green army men, led by Sarge, spy on the party, and report the results to the others via baby monitors. The toys are relieved when the party appears to end with none of them having been replaced, but then Andy receives a surprise gift – an electronic toy space ranger action figure named Buzz Lightyear, who thinks he is an actual space ranger. Buzz impresses the other toys with his various features, and Andy begins to favor him, making Woody feel left out. As Andy prepares for a family outing at Pizza Planet, his mother allows him to bring one toy. Fearing Andy will choose Buzz, Woody attempts to trap Buzz behind a desk, but ends up accidentally knocking him out a window, and the other toys rebel against Woody by accusing him of knocking Buzz out of jealousy. Before they can exact revenge, Andy takes Woody instead and leaves for Pizza Planet. When the family stops for gas, Woody finds that Buzz has hitched a ride on the car as well, and fight, only to find the family has left without them. They manage to make their way to the restaurant by stowing away on a pizza delivery truck, where Buzz, still thinking he is a real space ranger, despite Woody's attempts to convince him otherwise, gets them stuck in a crane game, where they are salvaged by Andy's mischievous neighbor, Sid Phillips. Woody attempts to escape from Sid's house, but Buzz, finally realizing he is a toy after watching a Buzz Lightyear TV ad, sinks into despondency. Sid plans to launch Buzz on a firework rocket, but his plans are delayed by a thunderstorm. Woody tells Buzz about the joy he can bring to Andy as a toy, restoring his confidence. The next day, Woody and Sid's mutant toy creations rescue Buzz just as Sid is about to launch the rocket and scare Sid into no longer abusing toys by coming to life in front of him, and he runs into his house screaming in horror. Woody and Buzz then leave Sid's house just as Andy and his family drive away toward their new home. The duo tries to make it to the moving truck, but Sid's dog, Scud, sees them, and gives chase. Buzz gets left behind while saving Woody from Scud, and Woody tries rescuing him with Andy's RC car, but the other toys, thinking Woody eliminated RC as well, attack and toss him off the truck. Having evaded Scud, Buzz and RC retrieve Woody, and continue after the truck. Upon seeing Woody and Buzz together on RC, the other toys realize their mistake, and try to help them get back aboard, but RC's batteries become depleted, stranding them. Woody ignites the rocket on Buzz's back and manages to throw RC into the truck before they soar into the air. Buzz opens his wings to free himself from the rocket before it explodes, gliding with Woody to land safely into a box in the car, right next to Andy. On Christmas Day, at their new house, Woody and Buzz stage another reconnaissance mission to prepare for the new toy arrivals. As Woody jokingly asks what might be worse than Buzz, they discover Andy's new gift is a puppy, and the two share a worried smile."

In [73]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45379 entries, 0 to 47083
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                45379 non-null  int64
 1   genres                45379 non-null  object
 2   id                    45379 non-null  int64
 3   original_language     45379 non-null  object
 4   original_title        45379 non-null  object
 5   overview              45379 non-null  object
 6   popularity            45379 non-null  float64
 7   production_companies  45378 non-null  object
 8   production_countries  45378 non-null  object
 9   release_date          45294 non-null  object
 10  revenue               45378 non-null  float64
 11  runtime               45379 non-null  float64
 12  spoken_languages      45378 non-null  object
 13  status                45297 non-null  object
 14  title                 45379 non-null  object
 15  vote_average          45379 non-null  float64
 16  vote_count            45379 non-null  float64
 17  keywords              45379 non-null  object
 18  cast                  45379 non-null  object
 19  crew                  45379 non-null  object
 20  movieId               45379 non-null  int64
 21  avg_rating            45379 non-null  float64
 22  rating_count          45379 non-null  float64
 23  title_clean           45378 non-null  object
 24  year                  45379 non-null  float64
 25  Plot                  45379 non-null  object
 26  Origin/Ethnicity      14741 non-null  object
 27  final_plot            45379 non-null  object
 28  genres_clean          45379 non-null  object
 29  keywords_clean        45379 non-null  object
 30  cast_clean            45379 non-null  object
 31  director_clean        45379 non-null  object
 32  combined_text         45379 non-null  object
dtypes: float64(8), int64(3), object(22)
memory usage: 12.8+ MB

In [75]:
(movies['combined_text'].str.len() < 20).sum()

np.int64(1)

In [79]:
movies[['title', 'year']].duplicated().sum()

np.int64(0)

In [80]:
movies['runtime'].describe()

count    45379.000000
mean        93.591088
std         38.958824
min          0.000000
25%         85.000000
50%         95.000000
75%        107.000000
max       1256.000000
Name: runtime, dtype: float64

In [81]:
movies['runtime'].head()

0     81.0
1    104.0
2    101.0
3    127.0
4    106.0
Name: runtime, dtype: float64

In [85]:
movies[movies['runtime'] > 300][['title', 'runtime']].sort_values('runtime', ascending=False)

                                    title  runtime
24648                          Centennial   1256.0
20339                                Jazz   1140.0
42524                            Baseball   1140.0
14016               Berlin Alexanderplatz    931.0
14210      Heimat: A Chronicle of Germany    925.0
...                                   ...      ...
43915                    Great Migrations    315.0
8043                           The Deluge    315.0
34584                   If Tomorrow Comes    313.0
40572  Anders Matthesen: Tal For Dig Selv    311.0
43622                   The Miracle Rider    306.0

[108 rows x 2 columns]

In [86]:
median_runtime = movies.loc[movies['runtime'] > 0, 'runtime'].median()
movies.loc[movies['runtime'] <= 0, 'runtime'] = median_runtime

In [87]:
movies.loc[movies['runtime'] > 300, 'runtime'] = 300

In [88]:
text_cols = ['combined_text', 'title', 'final_plot']
for col in text_cols:
    movies[col] = movies[col].astype(str)

In [89]:
movies = movies.reset_index(drop=True)

In [90]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45379 entries, 0 to 45378
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                45379 non-null  int64
 1   genres                45379 non-null  object
 2   id                    45379 non-null  int64
 3   original_language     45379 non-null  object
 4   original_title        45379 non-null  object
 5   overview              45379 non-null  object
 6   popularity            45379 non-null  float64
 7   production_companies  45378 non-null  object
 8   production_countries  45378 non-null  object
 9   release_date          45294 non-null  object
 10  revenue               45378 non-null  float64
 11  runtime               45379 non-null  float64
 12  spoken_languages      45378 non-null  object
 13  status                45297 non-null  object
 14  title                 45379 non-null  object
 15  vote_average          45379 non-null  float64
 16  vote_count            45379 non-null  float64
 17  keywords              45379 non-null  object
 18  cast                  45379 non-null  object
 19  crew                  45379 non-null  object
 20  movieId               45379 non-null  int64
 21  avg_rating            45379 non-null  float64
 22  rating_count          45379 non-null  float64
 23  title_clean           45378 non-null  object
 24  year                  45379 non-null  float64
 25  Plot                  45379 non-null  object
 26  Origin/Ethnicity      14741 non-null  object
 27  final_plot            45379 non-null  object
 28  genres_clean          45379 non-null  object
 29  keywords_clean        45379 non-null  object
 30  cast_clean            45379 non-null  object
 31  director_clean        45379 non-null  object
 32  combined_text         45379 non-null  object
dtypes: float64(8), int64(3), object(22)
memory usage: 11.4+ MB

In [91]:
movies.to_csv(r"C:\Users\HP\OneDrive\Desktop\AIML\Practice\Datasets\Movie recommendation\Master Dataset.csv", index=False)

In [92]:
movies.to_pickle(r"C:\Users\HP\OneDrive\Desktop\AIML\Practice\Datasets\Movie recommendation\Master Dataset.pkl")